name: Build Docker
on:
  push:
    branches:
      - "master"
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  docker:
    runs-on: self-hosted
    strategy:
      matrix:
        include:
          - tags:
              - ${{ ((github.event_name != 'pull_request') && format('{0}/reva:latest', secrets.DOCKERHUB_ORGANIZATION )) || '' }}
              - ${{ ((github.ref_type != 'tag') && format('{0}/reva:{1}', secrets.DOCKERHUB_ORGANIZATION, github.ref_name )) || '' }}
            file: Dockerfile.reva
        #  - tags: revad:latest
        #    file: Dockerfile.revad
        #  - tags: revad:latest-eos
        #    file: Dockerfile.revad-eos
        #  - tags: revad:latest-ceph
        #    file: Dockerfile.revad-ceph
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build ${{ ((github.event_name != 'pull_request') && 'and push') || '' }} ${{ matrix.tags }}
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          file: ${{ matrix.file }}
          tags: ${{ matrix.tags }}
