name: Docker
on:
  workflow_call:
    inputs:
      file:
        type: string
      tag:
        required: false
        type: string
      load:
        default: false
        required: false
        type: boolean

jobs:
  docker:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build ${{ inputs.tag }} Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ inputs.file }}
          tags: ${{ inputs.tag }}
          load: ${{ inputs.load }}
      - name: Upload ${{ inputs.tag }} Docker image to artifacts
        uses: ishworkh/docker-image-artifact-upload@v1
        if: ${{ inputs.load }}
        with:
          image: ${{ inputs.tag }}
          retention_days: '1'