name: golangci-lint
on:
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
        with:
          go-version-file: go.mod
      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.3.0