name: Check License
on:
  pull_request:
    paths-ignore: [".github/**", "Makefile", "tools/**", "docs/**", "tests/**", ".drone.star", ".drone.env", "go.mod", "go.sum"]

jobs:
  check-changelog:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Find license compliance and security issues
        uses: fossas/fossa-action@main
        with:
          api-key: ${{secrets.fossaApiKey}}
          run-tests: true