name: Release
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
        with:
          go-version-file: go.mod
      - name: Make distribution
        run: make dist VERSION=${{ github.ref_name }} GIT_COMMIT=${{ github.sha }} GO_VERSION=$(go version | awk '{print $3}')
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*"
          body_path: "changelog/NOTE.md"
  docker:
    runs-on: self-hosted
    strategy:
      matrix:
        include:
          - image: reva
            tag: reva:${{ github.ref_name }}
          - image: revad
            tag: revad:${{ github.ref_name }}
          - image: revad-eos
            tag: revad:${{ github.ref_name }}-eos
          - image: revad-ceph
            tag: revad:${{ github.ref_name }}-ceph
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push ${{ matrix.tag }}
        uses: docker/build-push-action@v3
        with:
          push: true
          file: docker/Dockerfile.${{ matrix.image }}
          tags: ${{ secrets.DOCKERHUB_ORGANIZATION }}/${{ matrix.tag }}
