name: Release
on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3.3.0
        with:
          go-version-file: go.mod
      - name: Make distribution
        run: make dist VERSION=${{ github.ref_name }} GIT_COMMIT=${{ github.sha }} GO_VERSION=$(go version | awk '{print $3}')
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "dist/*"
          body_path: "changelog/NOTE.md"
  docker:
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: reva
            tags: reva:${{ github.ref_name }}
          - image: revad
            tags: 
              - revad:${{ github.ref_name }}
              - latest
          - image: revad-eos
            tags: revad:${{ github.ref_name }}-eos
          - image: revad-ceph
            tags: revad:${{ github.ref_name }}-ceph
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      file: docker/Dockerfile.${{ matrix.image }}
      tags: ${{ toJSON(matrix.tags) }}
      push: true
